"@context": https://schema.org
"@type": SoftwareApplication
"@id": https://github.com/cyanheads/pubmed-mcp-server

additionalType:
  - https://schema.org/SoftwareSourceCode

identifier: cyanheads/pubmed-mcp-server

name: cyanheads/pubmed-mcp-server

description: >
  PubMed and EuropePMC search with full text access, MeSH terms and citations

codeRepository: https://github.com/cyanheads/pubmed-mcp-server

softwareHelp:
  "@type": CreativeWork
  url: https://github.com/cyanheads/pubmed-mcp-server#readme
  name: Documentation

maintainer:
  - "@type": Person
    name: Casey Hand
    identifier: cyanheads
    url: https://github.com/cyanheads

license: https://spdx.org/licenses/Apache-2.0.html

applicationCategory: HealthApplication

keywords:
  - EuropePMC
  - Medical literature
  - PubMed

datePublished: "2026-08-11"

operatingSystem:
  - Cross-platform

programmingLanguage:
  - TypeScript

featureList:
  - Full text retrieval
  - Citations
  - MeSH terms
