"@context": https://schema.org
"@type": SoftwareApplication
"@id": https://github.com/vrtejus/pymol-mcp

identifier: vrtejus/pymol-mcp

name: PyMOL-MCP

description: >
  PyMOL-MCP connects PyMOL to Claude AI through the Model Context Protocol (MCP), enabling Claude to directly
  interact with and control PyMOL. This powerful integration allows for conversational structural biology,
  molecular visualization, and analysis through natural language.

codeRepository: https://github.com/vrtejus/pymol-mcp

softwareHelp:
  "@type": CreativeWork
  url: https://github.com/vrtejus/pymol-mcp/blob/main/README.md
  name: Documentation

maintainer:
  - "@type": Person
    name: Vishnu Rajan Tejus
    identifier: vrtejus
    url: https://github.com/vrtejus

license: https://spdx.org/licenses/MIT.html

applicationCategory: HealthApplication

keywords:
  - PyMOL

featureList:
  - PyMOL

datePublished: "2025-06-12"

operatingSystem:
  - Cross-platform

programmingLanguage:
  - Python
