"@context": https://schema.org
"@type": SoftwareApplication
"@id": https://github.com/scmcphub/scmcp

identifier: scmcphub/scmcp

name: SCMCP

description: >
  An MCP server for scRNA-Seq analysis with natural language!

codeRepository: https://github.com/scmcphub/scmcp

softwareHelp:
  "@type": CreativeWork
  url: https://docs.scmcphub.org
  name: Documentation

maintainer:
  - "@type": Organization
    name: scmcphub
    identifier: scmcphub
    url: https://github.com/scmcphub/

license: https://spdx.org/licenses/BSD-3-Clause.html

applicationCategory: HealthApplication

keywords:
  - scmcp
  - single-cell
  - RNA sequencing
  - scverse

featureList:
  - decoupler
  - cellrank
  - liana
  - scanpy
  - infercnv

datePublished: "2025-06-11"

operatingSystem:
  - Cross-platform

programmingLanguage:
  - Python
