"@context": https://schema.org
"@type": SoftwareApplication
"@id": https://github.com/Augmented-Nature/BioThings-MCP-Server

identifier: Augmented-Nature/BioThings-MCP-Server

name: BioThings MCP Server

description: >
  A Model Context Protocol (MCP) server that provides access to the BioThings.io ecosystem of APIs, including
  MyGene.info and MyVariant.info. This server enables seamless integration of comprehensive gene and variant
  annotation data into your workflows.

codeRepository: https://github.com/Augmented-Nature/BioThings-MCP-Server

url: https://github.com/Augmented-Nature/BioThings-MCP-Server/blob/main/README.md

softwareHelp:
  "@type": CreativeWork
  url: https://github.com/Augmented-Nature/BioThings-MCP-Server/blob/main/README.md
  name: Documentation

maintainer:
  - "@type": Organization
    name: Augmented Nature
    identifier: Augmented-Nature
    url: https://github.com/Augmented-Nature

license: https://spdx.org/licenses/MIT.html

applicationCategory: HealthApplication

keywords:
  - BioThings
  - MyGene
  - MyVariant

datePublished: "2025-07-29"

operatingSystem:
  - Cross-platform

programmingLanguage:
  - TypeScript
