"@context": https://schema.org
"@type": SoftwareApplication
"@id": https://github.com/winninghealth/medcalcmcp

additionalType:
  - https://schema.org/SoftwareSourceCode

identifier: winninghealth/medcalcmcp

name: Medical Calculator MCP Service

description: >
  Medical Calculator MCP Service Implementation.

codeRepository: https://github.com/winninghealth/medcalcmcp

softwareHelp:
  "@type": CreativeWork
  url: https://github.com/winninghealth/medcalcmcp#readme
  name: Documentation

maintainer:
  - "@type": Organization
    name: Winning Health AI Research
    identifier: winninghealth
    url: https://github.com/winninghealth

license: https://spdx.org/licenses/Apache-2.0.html

applicationCategory: HealthApplication

keywords:
  - Medical Calculator

datePublished: "2025-10-17"

operatingSystem:
  - Cross-platform

programmingLanguage:
  - Python

featureList:
  - Clinical Scoring
