"@context": https://schema.org
"@type": SoftwareApplication
"@id": https://github.com/koido/gwas-catalog-mcp

identifier: koido/gwas-catalog-mcp

name: GWAS Catalog MCP Server

description: >
  This MCP server provides a programmatic interface to the GWAS Catalog REST API, enabling access to GWAS
  study, variant, trait, and association data. The server handles large result sets automatically by providing
  both in-memory results and file-based storage options.

codeRepository: https://github.com/koido/gwas-catalog-mcp

softwareHelp:
  "@type": CreativeWork
  url: https://github.com/koido/gwas-catalog-mcp/blob/main/README.md
  name: Documentation

maintainer:
  - "@type": Person
    name: Masaru Koido
    identifier: koido
    url: https://github.com/koido

license: https://spdx.org/licenses/Apache-2.0.html

applicationCategory: HealthApplication

keywords:
  - GWAS
  - EMBL

datePublished: "2025-06-11"

operatingSystem:
  - Cross-platform

programmingLanguage:
  - Python
