"@context": https://schema.org
"@type": SoftwareApplication
"@id": https://github.com/EBISPOT/gwas-mcp/

additionalType:
  - https://schema.org/SoftwareSourceCode

identifier: ebispot/gwas-mcp

name: GWAS Catalog MCP server

description: >
  GWAS Catalog Model Context Protocol server, supporting natural language queries of associations, studies, and traits

codeRepository: https://github.com/EBISPOT/gwas-mcp

url: https://ebi.ac.uk/gwas/mcp

softwareHelp:
  "@type": CreativeWork
  url: https://github.com/EBISPOT/gwas-mcp#readme
  name: Documentation

maintainer:
  - "@type": Person
    name: Benjamin Wingfield
    identifier: nebfield
    url: https://github.com/nebfield

license: https://spdx.org/licenses/Apache-2.0.html

applicationCategory: HealthApplication

keywords:
  - knowledgebase
  - gwas
  - genomics
  - gwas catalog

datePublished: "2026-07-01"

operatingSystem:
  - Cross-platform

programmingLanguage:
  - Python

featureList:
  - gwas catalog
