"@context": https://schema.org
"@type": SoftwareApplication
"@id": https://github.com/armish/hgnc.mcp/

additionalType:
  - https://schema.org/SoftwareSourceCode

identifier: armish/hgnc.mcp

name: hgnc

description: >
  This R package provides tools for accessing HGNC gene nomenclature data, including functions for searching, resolving, and validating gene symbols. It also includes an MCP (Model Context Protocol) server that exposes these tools to LLM copilots and other MCP-compatible clients.

codeRepository: https://github.com/armish/hgnc.mcp

softwareHelp:
  "@type": CreativeWork
  url: https://github.com/armish/hgnc.mcp#readme
  name: Documentation

maintainer:
  - "@type": Person
    name: B. Arman Aksoy
    identifier: armish
    url: https://github.com/armish

license: https://spdx.org/licenses/MIT.html

applicationCategory: ReferenceApplication

keywords:
  - gene
  - hgnc
  - human
  - bioinformatics
  - alias
  - mapping
  - uniprot
  - entrez
  - hugo

datePublished: "2025-11-21"

operatingSystem:
  - Cross-platform

programmingLanguage:
  - R

featureList:
  - Uniprot
  - Entrez
  - HGNC
  - HUGO
