"@context": https://schema.org
"@type": SoftwareApplication
"@id": https://github.com/PRIDE-Archive/mcp_pride_archive_search

additionalType:
  - https://schema.org/ScholarlyArticle
  - https://schema.org/SoftwareSourceCode

identifier: PRIDE-Archive/mcp_pride_archive_search

name: MCP PRIDE Archive Search Server

description: >
  This project implements a Model Context Protocol (MCP)-compliant API server that exposes tools to search
  the PRIDE Archive, a major repository for proteomics data.

codeRepository: https://github.com/PRIDE-Archive/mcp_pride_archive_search

maintainer:
  - "@type": Organization
    name: PRIDE-Archive
    identifier: PRIDE-Archive
    url: https://github.com/PRIDE-Archive

license: https://spdx.org/licenses/MIT.html

applicationCategory: HealthApplication

keywords:
  - PRIDE

datePublished: "2025-05-30"

operatingSystem:
  - Cross-platform

programmingLanguage:
  - Python
