"@context": https://schema.org
"@type": SoftwareApplication
"@id": https://github.com/longevity-genie/gget-mcp

identifier: longevity-genie/gget-mcp

name: Holy-BIO-MCP's gget server

description: >
  A Model Context Protocol server for the gget bioinformatics library. See details about gget: https://pachterlab.github.io/gget/

codeRepository: https://github.com/longevity-genie/gget-mcp

softwareHelp:
  "@type": CreativeWork
  url: https://github.com/longevity-genie/gget-mcp/blob/main/README.md
  name: Documentation

maintainer:
  - "@type": Person
    name: Anton Kulaga
    identifier: antonkulaga
    url: https://github.com/antonkulaga
  - "@type": Person
    name: Newton Winter
    identifier: winternewt
    url: https://github.com/winternewt

license: https://spdx.org/licenses/MIT.html

applicationCategory: UtilitiesApplication

keywords:
  - gget
  - holy-bio-mcp
  - bioinformatics
  - genomics
  - ncbi
  - enrichr
  - ensembl
  - uniprot
  - alphafold
  - ucsc

featureList:
  - Bioinformatics data retrieval and analysis
  - Multi-database genomics toolkit

datePublished: "2025-08-13"

operatingSystem:
  - Cross-platform

programmingLanguage:
  - Python
