"@context": https://schema.org
"@type": SoftwareApplication
"@id": https://github.com/noahzeidenberg/ncbi-mcp

additionalType:
  - https://schema.org/ScholarlyArticle
  - https://schema.org/SoftwareSourceCode

identifier: noahzeidenberg/ncbi-mcp

name: MCP Simple PubMed

description: >
  A Python implementation of the Model Context Protocol for interacting with NCBI databases.

codeRepository: https://github.com/noahzeidenberg/ncbi-mcp

maintainer:
  - "@type": Person
    name: Noah Zeidenberg
    identifier: noahzeidenberg
    url: https://github.com/noahzeidenberg

license: https://spdx.org/licenses/Apache-2.0.html

applicationCategory: HealthApplication

keywords:
  - NCBI
  - python

datePublished: "2025-05-30"

operatingSystem:
  - Cross-platform

programmingLanguage:
  - Python
