"@context": https://schema.org
"@type": SoftwareApplication
"@id": https://github.com/longevity-genie/biothings-mcp

additionalType:
  - https://schema.org/ScholarlyArticle
  - https://schema.org/SoftwareSourceCode

identifier: longevity-genie/biothings-mcp

name: biothings-mcp

description: >
  MCP (Model Context Protocol) server for Biothings.io

codeRepository: https://github.com/longevity-genie/biothings-mcp

softwareHelp:
  "@type": CreativeWork
  url: https://example-mcp-server.readthedocs.io
  name: Documentation

maintainer:
  - "@type": Organization
    name: longevity-genie
    identifier: longevity-genie
    url: https://github.com/longevity-genie

license: https://spdx.org/licenses/MIT.html

applicationCategory: HealthApplication

keywords:
  - mygene.info
  - myvariant.info
  - mychem.info
  - python

datePublished: "2025-05-30"

operatingSystem:
  - Cross-platform

programmingLanguage:
  - Python
