"@context": https://schema.org
"@type": SoftwareApplication
"@id": https://github.com/gwas-catalog/mcp

additionalType:
  - https://schema.org/SoftwareSourceCode

identifier: gwas-catalog/mcp

name: GWAS Catalog MCP server

description: >
  Model Context Protocol server owned and maintained by the GWAS Catalog team, supporting natural-language searches
  for genome-wide association studies, EFO traits, diseases, phenotypes, genes, ancestry, and variant-trait associations
  with statistical results.

codeRepository: https://github.com/gwas-catalog/mcp

url: https://www.ebi.ac.uk/gwas/mcp

softwareHelp:
  "@type": CreativeWork
  url: https://github.com/gwas-catalog/mcp#readme
  name: Documentation

maintainer:
  - "@type": Organization
    name: GWAS Catalog team
    identifier: gwas-catalog
    url: https://github.com/gwas-catalog

license: https://spdx.org/licenses/Apache-2.0.html

applicationCategory: HealthApplication

keywords:
  - knowledgebase
  - gwas
  - genomics
  - gwas catalog

datePublished: "2026-07-01"

operatingSystem:
  - Cross-platform

programmingLanguage:
  - Python

featureList:
  - gwas catalog
