"@context": https://schema.org
"@type": SoftwareApplication
"@id": https://github.com/ToxMCP/toxmcp

additionalType:
  - https://schema.org/SoftwareSourceCode

identifier: ToxMCP/toxmcp

name: ToxMCP Suite

description: >
  Guardrailed, auditable agentic workflows for computational toxicology delivered via the Model Context Protocol (MCP), with modules for CompTox, ADMETlab, AOP, O-QT, and PBPK workflows.

codeRepository: https://github.com/ToxMCP/toxmcp

softwareHelp:
  "@type": CreativeWork
  url: https://github.com/ToxMCP/toxmcp/tree/main/docs
  name: ToxMCP Docs

maintainer:
  - "@type": Person
    name: Ivo Djidrovski
    identifier: Brhii56
    url: https://github.com/Brhii56
  - "@type": Organization
    name: ToxMCP Maintainers
    identifier: ToxMCP
    url: https://github.com/ToxMCP

license: https://spdx.org/licenses/Apache-2.0.html

applicationCategory: HealthApplication

datePublished: "2026-02-16"

operatingSystem:
  - Cross-platform

programmingLanguage:
  - Python
