"@context": https://schema.org
"@type": SoftwareApplication
"@id": https://github.com/not-a-feature/VEPmcp

identifier: not-a-feature/VEPmcp

name: Variant Effect Prediction using Ensembl

description: >
  VEPmcp is a Model Context Protocol (MCP) server for the Ensembl Variant Effect Predictor (VEP) API.
  It enables annotation and effect prediction of genetic variants, with full support for batch and single
  queries, and is designed for seamless integration with MCP-compatible clients.

codeRepository: https://github.com/not-a-feature/VEPmcp

softwareHelp:
  "@type": CreativeWork
  url: https://github.com/not-a-feature/VEPmcp/blob/main/README.md
  name: Documentation

maintainer:
  - "@type": Person
    name: Jules Kreuer
    identifier: not-a-feature
    url: https://github.com/not-a-feature/

license: https://spdx.org/licenses/MIT.html

applicationCategory: HealthApplication

keywords:
  - Variant Effect
  - Prediction
  - Ensemble
  - API

datePublished: "2025-07-16"

operatingSystem:
  - Cross-platform

programmingLanguage:
  - Python
