"@context": https://schema.org
"@type": SoftwareApplication
"@id": https://github.com/EBIBioStudies/biostudies-mcp-server

identifier: EBIBioStudies/biostudies-mcp-server

name: Biostudies MCP server

description: >
  POC implementation for an MCP server for BioStudies search.

codeRepository: https://github.com/EBIBioStudies/biostudies-mcp-server

softwareHelp:
  "@type": CreativeWork
  url: https://github.com/EBIBioStudies/biostudies-mcp-server/blob/main/README.md
  name: Documentation

maintainer:
  - "@type": Organization
    name: EMBL-EBI BioStudies
    identifier: EBIBioStudies
    url: https://github.com/EBIBioStudies

license: https://spdx.org/licenses/Apache-2.0.html

applicationCategory: HealthApplication

keywords:
  - EMBL-EBI
  - BioStudies

featureList:
  - Literature data

datePublished: "2025-06-11"

operatingSystem:
  - Cross-platform

programmingLanguage:
  - Python
