name: Create and deploy MCP JSON

on:
  release:
    types: [published]
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
  schedule:
    # Run on Mondays and Thursdays at 17:00 UTC
    - cron: "0 17 * * 1,4"

jobs:
  deploy-json:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache-dependency-path: "**/pyproject.toml"

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Generate MCP JSON
        run: |
          uv run create_mcp_json

      - name: Copy mcp.json
        run: |
          mkdir build
          cp mcp.json build/mcp.json

      - name: Get MCP Tools
        run: |
          uv run get_mcp_tools --config mcp.json --output build/mcp_tools.json

      - name: Build & Deploy Worker
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          preCommands: |
            npm install wrangler@latest
